services:
  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: autoflex-oracle
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: oracle
      APP_USER: autoflex
      APP_USER_PASSWORD: autoflex
    volumes:
      - ./db/schema.sql:/container-entrypoint-initdb.d/schema.sql